{
    "login": "streamich",
    "node_id": "MDQ6VXNlcjk3NzM4MDM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/9773803?v=4",
    "html_url": "https://github.com/streamich",
    "followers_url": "https://api.github.com/users/streamich/followers",
    "repos_url": "https://api.github.com/users/streamich/repos",
    "events_url": "https://api.github.com/users/streamich/events{/privacy}",
    "received_events_url": "https://api.github.com/users/streamich/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Va Da",
    "company": null,
    "blog": "",
    "location": "Switzerland",
    "email": null,
    "hireable": true,
    "bio": "Contributing to diverse public domain and OSS projects.",
    "twitter_username": null,
    "public_repos": 400,
    "public_gists": 14,
    "followers": 1789,
    "following": 603,
    "created_at": "2014-11-15T20:58:02Z",
    "updated_at": "2024-03-07T21:05:06Z"
}